#!/usr/bin/perl
use strict;
# Generate creature header
open(my $src,'>','src/creatures.h');
print $src
"#ifndef CREATURES_H
#define CREATURES_H
#include \"items.h\"
#include \"spells.h\"
#include \"types.h\"\n";
open(my $et,'<','src/creatures.c');
for (<$et>) {print $src "extern etype_t $1;\n" if (/^etype_t (\w*)=/)}
close($et);
print $src "#endif";
close($src);
# Generate spawnlist
open(my $src,'>','src/spawnlist.c');
print $src "#include \"spawnlist.h\"\netype_t *spawnlist[]={\n";
open(my $et,'<','src/creatures.c');
for (<$et>) {print $src "\t&$1,\n" if (/^etype_t (\w*)=/)}
close($et);
print $src "};\nint spawnlist_size=sizeof(spawnlist)/sizeof(etype_t *);";
close($src);
